//What is DOM?

console.log("Document Object Model is a Tree of Elements (Nodes) generated by Browser")

//JS Can Manupulate DOM
//We can interact between HTML and JS by using DOM
//We can control a DOM using JS


